package convert;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

/**
 * Convierte "net_divided.json" (con campos M0, I_minus, I_plus)
 * a un archivo PNML estilo Tina: "net_full_tina.xml".
 *
 * Solo se incluyen plazas (P1…PNp), transiciones (T1…TNt) y arcos.
 * Las posiciones se distribuyen en malla para separarlas.
 */
public class ConvertDividedToTina {
    public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            System.err.println("Uso: java generatedAndSubdivide.ConvertJsonToPnml <entrada.json> <salida.pnml>");
            System.exit(1);
        }
        File jsonFile = new File(args[0]);
        String pnmlFile = args[1];

        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(jsonFile);

        // Leer vector M0
        JsonNode m0Node = root.get("M0");
        int Np = m0Node.size();
        int[] M0 = new int[Np];
        for (int i = 0; i < Np; i++) {
            M0[i] = m0Node.get(i).asInt();
        }

        // Leer I_minus
        JsonNode imNode = root.get("I_minus");
        int[][] I_minus = new int[Np][];
        for (int i = 0; i < Np; i++) {
            JsonNode row = imNode.get(i);
            int Nt = row.size();
            I_minus[i] = new int[Nt];
            for (int j = 0; j < Nt; j++) {
                I_minus[i][j] = row.get(j).asInt();
            }
        }

        // Leer I_plus
        JsonNode ipNode = root.get("I_plus");
        int[][] I_plus = new int[Np][];
        for (int i = 0; i < Np; i++) {
            JsonNode row = ipNode.get(i);
            int Nt = row.size();
            I_plus[i] = new int[Nt];
            for (int j = 0; j < Nt; j++) {
                I_plus[i][j] = row.get(j).asInt();
            }
        }

        int Nt = (Np > 0 ? I_minus[0].length : 0);

        // Configurar posiciones en malla
        int placeX = 100;
        int placeY0 = 100;
        int placeYstep = 180;
        int transX = 300;
        int transY0 = 100;
        int transYstep = 180;

        try (PrintWriter pw = new PrintWriter(new FileWriter(pnmlFile))) {
            // Header PNML
            pw.println("<?xml version=\"1.0\"?>");
            pw.println("<!-- generated by ConvertJsonToPnml on " + java.time.LocalDateTime.now() + " -->");
            pw.println("<pnml xmlns=\"http://www.pnml.org/version-2009/grammar/pnml\">");
            pw.println(" <net id=\"net1\" type=\"http://www.pnml.org/version-2009/grammar/ptnet\">");
            pw.println("  <name><text>" + new File(pnmlFile).getName() + "</text></name>");
            pw.println("  <page id=\"page1\">");

            // Places
            for (int i = 0; i < Np; i++) {
                String pid = "p" + i;
                int y = placeY0 + i * placeYstep;
                pw.println("   <place id=\"" + pid + "\">");
                pw.println("    <name><text>p" + i + "</text><graphics><offset x=\"0\" y=\"-10\"/></graphics></name>");
                if (M0[i] > 0) {
                    pw.println("    <initialMarking><text>" + M0[i] + "</text></initialMarking>");
                }
                pw.println("    <graphics><position x=\"" + placeX + "\" y=\"" + y + "\"/></graphics>");
                pw.println("   </place>");
            }

            // Transitions
            for (int j = 0; j < Nt; j++) {
                String tid = "t" + j;
                int y = transY0 + j * transYstep;
                pw.println("   <transition id=\"" + tid + "\">");
                pw.println("    <name><text>t" + j + "</text><graphics><offset x=\"0\" y=\"0\"/></graphics></name>");
                pw.println("    <graphics><position x=\"" + transX + "\" y=\"" + y + "\"/></graphics>");
                pw.println("   </transition>");
            }

            // Arcs: I_minus = place -> transition
            int arcId = 0;
            for (int i = 0; i < Np; i++) {
                String pid = "p" + i;
                for (int j = 0; j < Nt; j++) {
                    int mult = I_minus[i][j];
                    for (int k = 0; k < mult; k++) {
                        pw.println("   <arc id=\"e" + (arcId++) + "\" source=\"" + pid + "\" target=\"t" + j + "\"/>");
                    }
                }
            }
            // Arcs: I_plus = transition -> place
            for (int i = 0; i < Np; i++) {
                String pid = "p" + i;
                for (int j = 0; j < Nt; j++) {
                    int mult = I_plus[i][j];
                    for (int k = 0; k < mult; k++) {
                        pw.println("   <arc id=\"e" + (arcId++) + "\" source=\"t" + j + "\" target=\"" + pid + "\"/>");
                    }
                }
            }

            pw.println("  </page>");
            pw.println(" </net>");
            pw.println("</pnml>");
        }

        System.out.println("Se generó PNML: " + pnmlFile);
    }
}

